### PR TITLE
[NOTICE TO REPO VIEWERS] Fix causal prescriptivism in "Fuzztives and OCs" 

### PR DESCRIPTION
**Pull request by Default-GitHub-Account**
While I understand that this may have been inspired by experiences you may have had as a system, it's incredibly harmful to tell people to assert things about a system's members simply because of the term they identify with.

### CODE REVIEW

**Comment by sleepingdragoninn** [comment]
🎉 This section already has a pending rework. 

Generally speaking, this repo is read-only - it being public is only a result of github not allowing private repos to have pages instances. Please understand that given  the intent of the site, the accessibility of this repo and our github profile through "knowing how github pages works" poses an unfortunate genuine risk to our safety.

**Comment by Default-GitHub-Account** [comment]
Good to see. And I understand completely, I was just frustrated enough to march up here anyway. Have you considered Neocities?

**Comment by sleepingdragoninn** [comment]
🎉 Yeahhh look, the bulk of PR got written in a flurry to try and fix the chaos of a bunch of green systems with nowhere to talk - And, at the time, there were no fictives in the system - now there's me, so, I've just been waiting until I can get my thoughts in order.

We'll look at neocities though, relatively generic.

**Comment by sleepingdragoninn** [comment]
♦️ To elaborate a little bit on the site though for you but also potential future readers - we generally think it's okay when someone thinks something in PR is wrong, or comes away at the end disagreeing with a few points. 

If PR is delivering its messages successfully, it should be providing a framework of understanding of how something like plurality fits into larger fields of identity study, philosophy, and religious/cultural studies - in a way that allows the reader to confidently disagree with something PR itself says later.

You yourself used the term "causal prescriptivism" to shoot down a paragraph that boils down to "a specific belief about your own origin is bad" due to poor wording and conception - that's great! I think that means we're doing a good job.

That said though - to anyone reading this - please don't do syscourse in our issues or PRs. Freely come away disagreeing with parts of PR - that's entirely acceptable results. 

Im gonna reopen this one for visibility, and retitle it.

**Comment by Default-GitHub-Account** [comment]
PR is a pretty good guide to some of the nuances of this stuff but I think I should be a bit more specific with my criticism: the fictive section is misinterpretable as implying that fictives *should* diverge, otherwise they're causing harm/limiting themselves. While it's possible to guess the specific phenomena that the last sentence in that section is referring to if you're in the know, it's not immediately obvious to everyone.

**Comment by sleepingdragoninn** [comment]
♦️ Yeah I'm with you there 100%

The section is Like That because it responded to some very specific kinds of harm we'd seen the most in past at the time (two years ago at this point) - but now I think we have the tenure (and a relevantly intersectional contributor) to add more nuance.

**Pull request closed without merging**
